" Match TODO comments
syntax region frrString start=/"/ skip=/\\"/ end=/"/
syntax keyword frrTodo TODO XXX FIXME NOTE contained
syntax match frrComment /!.*/ contains=frrTodo
syntax match frrIpv4 "\v<\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}>"
syntax match frrPrefixIpv4 "\v<\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\/\d{1,2}"

" Some extra characters to unclude in keywords
setlocal iskeyword+=-
" Match language specific keywords
" i[interface] matches :i,in,inter,...
syntax keyword frrSpecial
			\ log
			\ debug
syntax keyword frrType
			\ i[nterface]
			\ r[outer]
syntax keyword frrKeywords
			\ topology
			\ a
			\ abc
			\ abr
			\ abr-type
			\ absolute
			\ accept
			\ accept-lifetime
			\ accept-own
			\ accept-own-nexthop
			\ access-class
			\ access-list
			\ access-vlan
			\ ack
			\ activate
			\ active
			\ active-active
			\ active-time
			\ add
			\ addpath-tx-all-paths
			\ addpath-tx-bestpath-per-
			\ addr
			\ address
			\ address-family
			\ adj-packets
			\ admin-grp
			\ administrative
			\ advanced-vty
			\ advertise
			\ advertise-all-vni
			\ advertise-default-gw
			\ advertised-routes
			\ advertise-map
			\ advertisement-interval
			\ advertise-pip
			\ advertise-queue
			\ advertise-subnet
			\ advertise-svi-ip
			\ advertise-un-method
			\ adv-interval-option
			\ adv-router
			\ affinity
			\ aggr
			\ aggregate
			\ aggregate-address
			\ aggregation
			\ aggregator
			\ alerts
			\ all
			\ all-et
			\ all-links
			\ allocate
			\ allowas-in
			\ allow-ecmp
			\ allow-external-route-update
			\ allow-martians
			\ allow-outbound-policy
			\ always
			\ always-compare-med
			\ any
			\ area
			\ area-id
			\ area-password
			\ arp
			\ arp-cache
			\ as
			\ asbr
			\ asbr-summary
			\ as-external
			\ as-number
			\ as-override
			\ as-path
			\ as-path-access-list
			\ assert
			\ assert-internal
			\ assert-metric
			\ assert-winner-metric
			\ as-set
			\ atom
			\ atomic-aggregate
			\ attached-bit
			\ attribute-info
			\ attribute-unchanged
			\ auth
			\ authenticate
			\ authentication
			\ authentication-key
			\ auth-length
			\ auto
			\ autoconfigure
			\ auto-cost
			\ autort
			\ auto-summary
			\ auto-vn
			\ ava-bw
			\ babel
			\ babeld
			\ backdoor
			\ backup
			\ backup-group
			\ backup-idx
			\ bandwidth
			\ banner
			\ basic
			\ batch-tx-buf
			\ bestpath
			\ bestpath-routes
			\ bfd
			\ bfdd
			\ bgp
			\ bgpd
			\ bgp-direct
			\ bgp-direct-to-nve-groups
			\ bind
			\ binding-sid
			\ bindingt
			\ blackhole
			\ bmp
			\ bnc
			\ border-routers
			\ both
			\ bound
			\ boundary
			\ bridge
			\ brief
			\ broadcast
			\ bsm
			\ bsm-database
			\ bsr
			\ bsr-data
			\ bsrp-info
			\ buffer-limit
			\ bynversion
			\ bypass
			\ cache
			\ cache-connection
			\ cache-server
			\ call
			\ callbacks
			\ candidate-path
			\ candidate-pathtpreference
			\ capabilities
			\ capability
			\ ce
			\ chain
			\ channel
			\ check-control-plane-failure
			\ chunks
			\ cidr-only
			\ cigp
			\ circuit-type
			\ cisco
			\ cisco-interop
			\ clear
			\ cli
			\ client
			\ client-to-client
			\ close
			\ cluster-id
			\ coalesce-time
			\ color
			\ command
			\ commands
			\ comm-list
			\ common
			\ community
			\ community-info
			\ community-list
			\ compare-routerid
			\ compatible
			\ confed
			\ confederation
			\ config
			\ configuration
			\ configure
			\ connect
			\ connected
			\ connection
			\ continue
			\ controlnuthentication
			\ control-word
			\ copy
			\ cost
			\ count
			\ counters
			\ cpu
			\ critical
			\ cron
			\ csnp-interval
			\ cte
			\ cumulative
			\ daemon
			\ daemons
			\ dampened-paths
			\ dampened-routes
			\ dampening
			\ database
			\ dbdesc
			\ dc
			\ dd
			\ dead-interval
			\ dead-timer
			\ debugging
			\ default
			\ default-cost
			\ default-information
			\ default-metric
			\ default-originate
			\ default-route
			\ defaults
			\ defaultsn
			\ defaultsnnset
			\ default-weight-for-missing
			\ delay
			\ delayopen
			\ delay-timer
			\ delay-variation
			\ delegation-timeout
			\ delete
			\ deny
			\ description
			\ detail
			\ detailed
			\ detailt
			\ detect-multiplier
			\ deterministic-med
			\ disable
			\ disable-connected-check
			\ disabled
			\ disable-ead-evi-rx
			\ disable-ead-evi-tx
			\ disable-ebgp-connected-route-check
			\ disable-eor
			\ discovery
			\ distance
			\ distributed
			\ distribute-list
			\ diversity
			\ diversity-factor
			\ dnssl
			\ doc:
			\ domain
			\ domain-password
			\ done
			\ dont-capability-negotiate
			\ down
			\ downstream
			\ dplane
			\ drchoice
			\ drpriority
			\ dscp
			\ dst-ip
			\ dual-stack
			\ dump
			\ dup-addr
			\ dup-addr-detection
			\ duplicate
			\ duration
			\ dynamic
			\ dynamict
			\ ead
			\ ebgp-multihop
			\ ebgp-requires-policy
			\ echo
			\ echo-interval
			\ echo-mode
			\ ecmp
			\ ecn
			\ egate
			\ egp
			\ eigrp
			\ eigrpd
			\ emergencies
			\ enable
			\ enable-timestamps
			\ encap-attr
			\ end
			\ endpoint
			\ enforce-first-as
			\ enforce-multihop
			\ equal-cluster-length
			\ error
			\ errors
			\ es
			\ es-df-pref
			\ es-evi
			\ esi
			\ es-id
			\ es-sys-mac
			\ established
			\ es-vrf
			\ et
			\ ethernet
			\ ethernet-tagged
			\ ethtag
			\ event
			\ events
			\ eventst
			\ evpn
			\ exact
			\ exact-match
			\ examine
			\ exclude
			\ exclude-any
			\ exec-timeout
			\ exist-map
			\ exit
			\ exit-address-family
			\ exit-link-params
			\ exit-vnc
			\ exit-vni
			\ exit-vrf
			\ exit-vrf-policy
			\ expanded
			\ expire_interval
			\ explicit
			\ explicit-null
			\ explicit-nullt
			\ export
			\ export-list
			\ extcommunity
			\ extcommunity-list
			\ extended
			\ extended-nexthop
			\ external
			\ external-
			\ fabricd
			\ fabric-tier
			\ facility
			\ failed
			\ fast-external-failover
			\ fast-reroute
			\ fec
			\ fib
			\ file
			\ fill
			\ filter
			\ filtered-routes
			\ filter-list
			\ find
			\ first-match
			\ flag
			\ flap-statistics
			\ flooding
			\ flowspec
			\ flowspec...
			\ follownhe
			\ for
			\ force
			\ format
			\ forwarding
			\ forwarding-address
			\ fpm
			\ freeze
			\ from
			\ frr
			\ ge
			\ generate
			\ generate-query-once
			\ gen-interval
			\ global
			\ global-block
			\ goto
			\ graceful-restart
			\ graceful-restart-disable
			\ graceful-restart-helper
			\ graceful-shutdown
			\ graph
			\ group
			\ group-membership
			\ group-nve
			\ groups
			\ group-type
			\ gwip
			\ hash
			\ hashtable
			\ hc
			\ head-end-replication
			\ hello
			\ hello-interval
			\ hello-multiplier
			\ helper
			\ helper-only
			\ high
			\ history
			\ hmac-sha-
			\ holddown
			\ hold-time
			\ holdtime
			\ home-agent-config-flag
			\ home-agent-lifetime
			\ home-agent-preference
			\ hops
			\ host
			\ hostname
			\ host-routes
			\ ibgp
			\ ibm
			\ identifier
			\ ifmtu
			\ igmp
			\ ignore
			\ igp
			\ igp-sync
			\ implicit-null
			\ import
			\ import-bi-attach
			\ import-check
			\ import-check-table
			\ import-del-remote
			\ imported
			\ import-list
			\ import-rt
			\ import-table
			\ in
			\ inbound
			\ include
			\ include-all
			\ include-any
			\ incomplete
			\ index
			\ infinite
			\ infinity-and-beyond
			\ informational
			\ informationnouting
			\ init-delay
			\ install
			\ instance-id
			\ integrated
			\ integrated-vtysh-config
			\ inter-area
			\ inter-as
			\ interfaces
			\ interfering
			\ internal
			\ inter-prefix
			\ inter-router
			\ interval
			\ intra-area
			\ intra-prefix
			\ inuse
			\ invalid
			\ ip
			\ ip_rip_authentication_string_cmd_vtysh:
			\ ipset
			\ iptable
			\ ipv
			\ ipv-dstsrc
			\ ipv-mgmt
			\ ipv-multicast
			\ ipv-unicast
			\ ipvunicast
			\ irdp
			\ isis
			\ isisd
			\ ism
			\ is-type
			\ its
			\ join
			\ join-prune-interval
			\ joins
			\ jp-agg
			\ json
			\ keep-alive
			\ keepalive-reset
			\ keepalives
			\ keep-alive-timer
			\ kern
			\ kernel
			\ key
			\ key-chain
			\ keyn,
			\ key-string
			\ key_string_cmd_vtysh:
			\ kill
			\ label
			\ labeled-unicast
			\ label-index
			\ labelpool
			\ labels
			\ large
			\ large-comm-list
			\ large-community
			\ large-community-info
			\ large-community-list
			\ last-as
			\ last-member-query-count
			\ last-member-query-interval
			\ ldp
			\ ldpd
			\ ldp-sync
			\ le
			\ leak-from-vrf
			\ leak-to-vrf
			\ ledger
			\ length
			\ level
			\ level-
			\ level--
			\ level--only
			\ lfa
			\ l-group
			\ libyangt
			\ lifetime
			\ limit
			\ line
			\ link
			\ link-detect
			\ link-params
			\ linkstate
			\ linkstate-id
			\ list
			\ listen
			\ listener
			\ listeners
			\ llgr-stale
			\ lmll
			\ l-nh
			\ lni
			\ load-sharing
			\ local
			\ local-
			\ local-address
			\ local-as
			\ local-block
			\ local-install
			\ local-label
			\ local-mac
			\ local-membership
			\ local-preference
			\ log-adjacency-changes
			\ logging
			\ logical-network-id
			\ login
			\ log-neighbor-changes
			\ long-delay
			\ longer
			\ longer-prefix
			\ longer-prefixes
			\ longer-prefixest
			\ low
			\ lower-distance
			\ lowest-backup-metric
			\ lpr
			\ lrd
			\ lsa
			\ ls-ack
			\ lsack
			\ lsp
			\ lsp-gen
			\ lsp-gen-interval
			\ lsp-mtu
			\ lsp-refresh-interval
			\ lsp-sched
			\ lsp-timers
			\ lsreq
			\ ls-request
			\ lsr-id
			\ ls-update
			\ lsupdate
			\ lvpn
			\ mac
			\ macaddr
			\ mac-holdtime
			\ macip
			\ mac-ip-es
			\ mail
			\ managed-config-flag
			\ map
			\ mark
			\ martian
			\ mask
			\ match
			\ matching--only
			\ max
			\ maxadvertinterval
			\ max-age
			\ max-bw
			\ maximum-metric
			\ maximum-paths
			\ maximum-prefix
			\ maximum-prefix-out
			\ max-lifetime
			\ max-lsp-lifetime
			\ max-med
			\ max-metric
			\ max-moves
			\ max-peer-dead-timer
			\ max-peer-keep-alive
			\ max-retry
			\ max-rsv-bw
			\ max-rtt-penalty
			\ mbc
			\ mbn
			\ mbp
			\ mcc
			\ mcp
			\ mct
			\ mctd
			\ md
			\ med
			\ medium
			\ member
			\ memory
			\ memstats-at-exit
			\ mesh-group
			\ message
			\ message-digest
			\ message-digest-key
			\ messages
			\ metric
			\ metric-style
			\ metric-type
			\ mh
			\ min
			\ minadvertinterval
			\ min-arrival
			\ minimal
			\ minimum-ttl
			\ min-peer-dead-timer
			\ min-peer-keep-alive
			\ min-retry
			\ mirror
			\ misc
			\ missing-as-worst
			\ mlag
			\ mll
			\ mlp
			\ mode
			\ modules
			\ monitor
			\ motd
			\ mplp
			\ mpls
			\ mpls-ldp
			\ mpls-te
			\ mrib-only
			\ mrib-then-urib
			\ mroute
			\ mrup
			\ msd
			\ msdp
			\ msec
			\ msgdump
			\ msl
			\ msn
			\ mss
			\ mtd
			\ mtrace
			\ mtu
			\ mtu-ignore
			\ multicast
			\ multihop
			\ multipath
			\ multipath-relax
			\ mup
			\ nai
			\ name
			\ nap
			\ narrow
			\ nd
			\ ndisc
			\ neigh
			\ neighbor
			\ neighbor-events
			\ neighbors
			\ neigh-holdtime
			\ net
			\ netlink
			\ netns
			\ network
			\ news
			\ next
			\ next-hop
			\ nexthop
			\ nexthop-group
			\ nexthop-groups
			\ nexthop-local
			\ nexthop-lookup
			\ next-hops
			\ next-hop-self
			\ nexthop-vrf
			\ n-flag-clear
			\ nformation
			\ nh
			\ nht
			\ nlp
			\ no
			\ no-advertise
			\ no-as-set
			\ no-autoconfig
			\ node
			\ node-msd
			\ node-protecting
			\ node-protection
			\ no-export
			\ no-header
			\ no_ip_rip_authentication_string_cmd_vtysh:
			\ no_key_string_cmd_vtysh:
			\ no-llgr
			\ non-broadcast
			\ none
			\ non-exist-map
			\ noninterfering
			\ non-transitive
			\ nopassword
			\ no-peer
			\ no-php-flag
			\ no-prepend
			\ no-rib
			\ northboundt
			\ no-summary
			\ not-advertise
			\ notfound
			\ notifications
			\ notificationst
			\ nsm
			\ nssa
			\ nssa-external
			\ null
			\ num-multipaths
			\ nve
			\ nve-group
			\ nves
			\ objective-function
			\ odify
			\ of
			\ off
			\ off-link
			\ offset-list
			\ oil
			\ old-ripd
			\ on
			\ onfigure
			\ onlink
			\ only
			\ on-match
			\ on-shutdown
			\ on-startup
			\ opaque
			\ opaque-area
			\ opaque-as
			\ opaque-link
			\ opaque-lsa
			\ open
			\ openfabric
			\ operational-data
			\ optimization
			\ or
			\ ordered-control
			\ orf
			\ origin
			\ originate
			\ originator-id
			\ ospf
			\ ospfd
			\ other-config-flag
			\ out
			\ outing
			\ output
			\ overlay
			\ overload
			\ override-capability
			\ packet
			\ packet-dump
			\ packet-loss
			\ packet-queue
			\ packets
			\ padding
			\ paginate
			\ parameters
			\ parametersnset
			\ parametersnssign
			\ parametersnversion
			\ passive
			\ passive-interface
			\ passive-mode
			\ password
			\ password-encryption
			\ passwordnpecifies
			\ path
			\ pathd
			\ pathd-pcep
			\ paths
			\ pbr
			\ pbrd
			\ pbr-map
			\ pbr-policy
			\ pcc
			\ pce
			\ pce-config
			\ pce-initiated
			\ pcep
			\ pceplib
			\ pcep-request
			\ pd
			\ pdv
			\ peer
			\ peer-address
			\ peer-group
			\ peerhash
			\ peers
			\ permanent
			\ permit
			\ permutations
			\ phc
			\ pigp
			\ pim
			\ pimd
			\ ping
			\ pl
			\ plain
			\ planned-only
			\ point-to-multipoint
			\ point-to-point
			\ poisoned-reverse
			\ policy
			\ poll
			\ polling_period
			\ poll-interval
			\ port
			\ post-policy
			\ ppd
			\ ppdv
			\ ppl
			\ precedence
			\ precision
			\ preempt
			\ prefer
			\ preference
			\ prefer-global
			\ prefix
			\ prefix-counts
			\ prefix-filter
			\ prefix-len
			\ prefix-list
			\ prefix-priority
			\ prefix-sid
			\ prefix-table
			\ prepend
			\ pre-policy
			\ preserve-fw-state
			\ primary
			\ priority
			\ priority-limit
			\ privileged
			\ proactive-arp
			\ probability
			\ probe
			\ process
			\ profile
			\ proto
			\ protocol
			\ providers
			\ pseudowire
			\ pseudowires
			\ psnp-interval
			\ pte
			\ purge-originator
			\ pw-id
			\ pw-status
			\ queries
			\ query
			\ query-interval
			\ query-max-response-time
			\ query-max-response-time-dsec
			\ quit
			\ ra-fast-retrans
			\ ra-hop-limit
			\ ra-interval
			\ ra-lifetime
			\ range
			\ ra-retrans-interval
			\ rd
			\ rdnss
			\ reachable-time
			\ read-quanta
			\ rebalance
			\ receive
			\ received
			\ received-routes
			\ receive-interval
			\ record-priority
			\ recv
			\ redirect
			\ redirect-off
			\ redistribute
			\ reference-bandwidth
			\ reflection
			\ refresh
			\ refresh-interval
			\ regexp
			\ register
			\ register-accept-list
			\ registering-nve
			\ register-suppress-time
			\ registrations
			\ reject
			\ reject-as-sets
			\ remark
			\ remote
			\ remote-as
			\ remote-label
			\ remote-lfa
			\ removed
			\ remove-private-
			\ replace-
			\ replace-as
			\ reply
			\ request
			\ requests
			\ required
			\ res-bw
			\ resend-delay
			\ reset
			\ resolve-nve
			\ resolve-via-default
			\ response-lifetime
			\ response-omit-self
			\ responses
			\ restart
			\ restart-time
			\ retransmissions
			\ retransmit-interval
			\ retry
			\ retry_interval
			\ rfapi-dev
			\ rfapi-query
			\ rfc
			\ rfccompatibility
			\ rfc-compatible
			\ rfd
			\ rib
			\ rib-stale-time
			\ rip
			\ ripd
			\ ripng
			\ ripngd
			\ rmac
			\ rmap-event
			\ ro
			\ role
			\ roo-ec-local-admin
			\ rotocolnuthentication
			\ route
			\ route-events
			\ route-filter-translated-v
			\ route-filter-v
			\ route-leak
			\ route-map
			\ route-map-unused
			\ router-address
			\ route-reflector
			\ route-reflector-client
			\ router-id
			\ router-info
			\ router-lsa
			\ routermac
			\ router-preference
			\ routes
			\ route-server-client
			\ routes-mrt
			\ route-source
			\ routet.../
			\ route-target
			\ route-type
			\ rp
			\ rpct
			\ rpf
			\ rpf-lookup-mode
			\ rp-info
			\ rpki
			\ rt
			\ rtt
			\ rtt-decay
			\ rtt-max
			\ rtt-min
			\ running
			\ running-config
			\ rxcost
			\ sa
			\ scope
			\ secondary
			\ segment
			\ segment-list
			\ segment-routing
			\ select-defer-time
			\ self
			\ self-originate
			\ self-originated
			\ send
			\ send-community
			\ sender-as-path-loop-detection
			\ send-extra-data
			\ send-lifetime
			\ send-only
			\ send-v-secondary
			\ sent
			\ seq
			\ sequence-number
			\ service
			\ session
			\ session-timeout-interval
			\ set
			\ set-attached-bit
			\ set-overload-bit
			\ sharp
			\ shortcut
			\ short-delay
			\ show
			\ show-hostname
			\ show-nexthop-hostname
			\ shutdown
			\ siaquery
			\ siareply
			\ simulate
			\ singlehop
			\ singleton
			\ skip-missing
			\ sm
			\ smoothing-half-life
			\ snp
			\ snp-packets
			\ sockets
			\ soft
			\ soft-reconfiguration
			\ solo
			\ soo
			\ source
			\ source-address
			\ source-instance
			\ source-protocol
			\ sources
			\ source-vrf
			\ spf
			\ spf-delay-ietf
			\ spf-events
			\ spf-interval
			\ spf-tree
			\ split-horizon
			\ spt
			\ spt-switchover
			\ sr
			\ src
			\ src-ip
			\ sr-draft
			\ sr-events
			\ sr-te
			\ ssm
			\ ssmpingd
			\ stalepath-time
			\ standard
			\ start
			\ startup-config
			\ startup-delay(-)
			\ state
			\ static
			\ staticd
			\ statistics
			\ statistics-all
			\ stats
			\ status
			\ stdout
			\ stop
			\ strict-capability-match
			\ strict-lsa-checking
			\ string
			\ string:
			\ stringn,
			\ stringnhe
			\ stringnuthentication
			\ stub
			\ stub-router
			\ subgroup-pkt-queue-max
			\ substitute
			\ summary
			\ summary-address
			\ summary-only
			\ supernets-only
			\ supported-grace-time
			\ suppress-duplicates
			\ suppress-fib-pending
			\ suppress-map
			\ suppress-ra
			\ sync
			\ synchronization
			\ syslog
			\ t
			\ t...
			\ table
			\ table-map
			\ tag
			\ tags
			\ target
			\ targeted
			\ targeted-hello
			\ targets
			\ tcp-md-auth
			\ te
			\ terminal
			\ terse
			\ test
			\ text
			\ the
			\ thread
			\ three-way-handshake
			\ throttle
			\ tiebreaker
			\ ti-lfa
			\ time
			\ timeout
			\ timer
			\ timers
			\ timestamp
			\ time-to-learn
			\ to
			\ topology
			\ topologyipv-unicast
			\ trace
			\ traceroute
			\ traffic
			\ traffic-eng
			\ transition
			\ translate
			\ translate-always
			\ translate-candidate
			\ translate-never
			\ transmit
			\ transmit-delay
			\ transmit-interval
			\ transport-address
			\ transport-connection
			\ tree
			\ treject
			\ triggered-csnp-delay
			\ tt
			\ ttl-security
			\ tunnel
			\ tx-queue
			\ type
			\ type-
			\ ull
			\ un
			\ unchanged
			\ unicast
			\ unicast-bsm
			\ unknown
			\ unregister
			\ unrsv-bw
			\ unsuppress-map
			\ up
			\ update
			\ update-delay
			\ update-groups
			\ update-interval
			\ update-packets
			\ updates
			\ updates-et
			\ update-source
			\ uplink
			\ upstream
			\ upstream-join-desired
			\ upstream-rpf
			\ urib-only
			\ use-bw
			\ usednprofile
			\ use-es-lnhg
			\ use-next-hop-groups
			\ user
			\ username
			\ use-source
			\ uthentication
			\ uthenticationn-
			\ uucp
			\ valid
			\ validate
			\ variance
			\ v-broadcast
			\ vc
			\ vc-id
			\ vct
			\ verbose
			\ version
			\ view
			\ views
			\ virtual-link
			\ virtual-network-identifier
			\ vn
			\ vnc
			\ vnc-direct
			\ vni
			\ vonly
			\ vpls
			\ vpn
			\ vrf
			\ vrf-import-rt
			\ vrf-policy
			\ vrfs
			\ vrrp
			\ vrrpd
			\ vtep
			\ vty
			\ vxlan
			\ vxlan-groups
			\ vxlan-work
			\ wait-for-sync
			\ warning-only
			\ warnings
			\ was
			\ watchfrr
			\ watermark-warn
			\ weight
			\ weights
			\ wide
			\ will
			\ wired
			\ wireless
			\ with-defaultszebra
			\ work-queue
			\ work-queues
			\ write
			\ write-multiplier
			\ write-quanta
			\ written
			\ xml
			\ xmlt
			\ yang
			\ zapi-packets
			\ zebra

highlight default link frrTodo Todo
highlight default link frrString String
highlight default link frrComment Comment
highlight default link frrKeywords Keyword
highlight default link frrSpecial Special
highlight default link frrType Type
highlight default link frrIpv4 Number
highlight default link frrPrefixIpv4 Number


